spring.security.oauth2.client:
  registration:
    az:
      authorization-grant-type: "client_credentials"
      # asb-test -- app registration name
      client-id: ${AZ_CLIENT_ID}
      client-secret: ${AZ_CLIENT_SECRET}
      client-authentication-method: "client_secret_post"
      scope: "https://graph.microsoft.com/.default"

  provider:
    az:
      # 4da31ef7-... -- tenantId
      token-uri: "https://login.microsoftonline.com/4da31ef7-.../oauth2/v2.0/token"
