spring.security.oauth2.client:
  registration:
    az-one:
      authorization-grant-type: "client_credentials"
      client-name: "asb-test"
      client-id: ${AZ_CLIENT_ID_TWO}
      client-secret: ${AZ_CLIENT_SECRET_ONE}
      client-authentication-method: "client_secret_post"
      scope: "https://graph.microsoft.com/.default"
      provider: "az"
    az-two:
      authorization-grant-type: "client_credentials"
      client-name: "asb-test"
      client-id: ${AZ_CLIENT_ID_TWO}
      client-secret: ${AZ_CLIENT_SECRET_TWO}
      client-authentication-method: "client_secret_post"
      scope: "https://graph.microsoft.com/.default"
      provider: "az"

  provider:
    az:
      # 4da31ef7-... -- tenantId
      token-uri: "https://login.microsoftonline.com/4da31ef7-/oauth2/v2.0/token"

logging.level:
  org.springframework.web.client: DEBUG
